export declare const DLWidget: import("vue").DefineComponent<Readonly<{
    onError?: any;
    name?: any;
    entry?: any;
    extra?: any;
    advanced?: any;
    collect?: any;
    loader?: any;
    onBeforeLoad?: any;
    onBeforeMount?: any;
    onAfterMount?: any;
    onBeforeUnmount?: any;
    onAfterUnmount?: any;
}>, () => JSX.Element, unknown, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, import("vue").VNodeProps & import("vue").AllowedComponentProps & import("vue").ComponentCustomProps, Readonly<import("vue").ExtractPropTypes<Readonly<{
    onError?: any;
    name?: any;
    entry?: any;
    extra?: any;
    advanced?: any;
    collect?: any;
    loader?: any;
    onBeforeLoad?: any;
    onBeforeMount?: any;
    onAfterMount?: any;
    onBeforeUnmount?: any;
    onAfterUnmount?: any;
}>>>, {
    readonly onError?: any;
    readonly name?: any;
    readonly entry?: any;
    readonly extra?: any;
    readonly advanced?: any;
    readonly collect?: any;
    readonly loader?: any;
    readonly onBeforeLoad?: any;
    readonly onBeforeMount?: any;
    readonly onAfterMount?: any;
    readonly onBeforeUnmount?: any;
    readonly onAfterUnmount?: any;
}>;
